In [18]:
# Create a numpy array called grades
import numpy as np
grades = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [19]:
# Using the numpy functions to calculate the mean of the grades
np.mean(grades)

87.5

In [20]:
# Using the numpy functions to calculate the median of the grades
np.median(grades)

88.5

In [21]:
# Using the numpy functions to calculate the standard deviation of the grades
np.std(grades1)

6.591661399070799

In [22]:
# Using the numpy functions to find the maximum of the grades
np.max(grades)

98

In [23]:
# Using the numpy functions to find the minimum of the grades
np.min(grades)

75

In [24]:
# Using the numpy function to sort the grades in ascending order.
np.sort(grades)

array([75, 80, 83, 85, 88, 89, 90, 92, 95, 98])

In [25]:
# Using the numpy function to find the index of the highest grade in the array.
np.argmax(grades)

7

In [27]:
# Using the numpy function to count the number of students who scored above 90.
np.count_nonzero(grades > 90)

3

In [28]:
# Using the numpy function to calculate the percentage of students who scored above 90.
np.mean(grades > 90) * 100

30.0

In [29]:
# Using the numpy function to calculate the percentage of students who scored below 75.
np.mean(grades < 75) * 100

0.0

In [30]:
# Using the numpy function to extract all the grades above 90 and put them in a new array called "high_performers".
high_performers = grades[grades > 90]

In [31]:
high_performers

array([92, 95, 98])

In [32]:
# Creating a new array called "passing_grades" that contains all the grades above 75.
passing_grades = grades[grades > 75]

In [33]:
passing_grades

array([85, 90, 88, 92, 95, 80, 98, 89, 83])

In [46]:
# Printing the result of all the above steps.
print( f" This is the result for mean of grades = {np.mean(grades)} ")
print(f" This is the result for median of grades = {np.median(grades)} ")
print(f" This is the result for standard deviation of grades = {np.std(grades1)} ")
print(f" This is the result for maximum number of grades = {np.max(grades)} ")
print(f" This is the result for total number of students with grade above 90 = {np.count_nonzero(grades > 90)} ")
print(f" This is the result for percentage of grades above 90 = {np.mean(grades > 90) * 100} ")
print(f" This is the result for percentage of grades below 75 = {np.mean(grades < 75) * 100} ")
print(f" This is the list of High Performers = {high_performers} ")
print(f" This is the list of Passing Grades = {passing_grades} ")

 This is the result for mean of grades = 87.5 
 This is the result for median of grades = 88.5 
 This is the result for standard deviation of grades = 6.591661399070799 
 This is the result for maximum number of grades = 98 
 This is the result for total number of students with grade above 90 = 3 
 This is the result for percentage of grades above 90 = 30.0 
 This is the result for percentage of grades below 75 = 0.0 
 This is the list of High Performers = [92 95 98] 
 This is the list of Passing Grades = [85 90 88 92 95 80 98 89 83] 
